package PrimeraEntrega.Presentacion.Cliente;

import javax.swing.JOptionPane;

import PrimeraEntrega.Negocio.Transfer.TransferCliente;
import PrimeraEntrega.Negocio.Transfer.TransferClienteStandar;
import PrimeraEntrega.Negocio.Transfer.TransferClienteVip;
import PrimeraEntrega.Presentacion.Vista;
import PrimeraEntrega.Presentacion.Controlador.Evento;
import PrimeraEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import PrimeraEntrega.Presentacion.Dispatcher.EventoVista;


public class GUIMostrarCliente extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form GUIMostrarCliente
     */
	static private GUIMostrarCliente mostrarCliente;

	  /** Creates new form NuevoDepartamento */
	  private GUIMostrarCliente() {
	      initComponents();
	  }
	  
	  /**
	   * Obtiene la instancia de la ventana
	   * @return la instancia de la ventana
	   */
	  static public GUIMostrarCliente obtenerInstancia(){
		   if(mostrarCliente == null){
			   mostrarCliente = new GUIMostrarCliente();
		   }
		   
		   return mostrarCliente;
	  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jRadioButtonTipo = new javax.swing.JRadioButton();
        jRadioButtonTipo.setEnabled(false);
        jLabelDNI = new javax.swing.JLabel();
        jLabelDescuento = new javax.swing.JLabel();
        jLabelPuntos = new javax.swing.JLabel();
        jFormattedTextFieldNombre = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombre.setEnabled(false);
        jFormattedTextFieldApellidos = new javax.swing.JFormattedTextField();
        jFormattedTextFieldApellidos.setEnabled(false);
        jFormattedTextFieldDNI = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPuntos = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPuntos.setEnabled(false);
        jFormattedTextFieldDescuento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDescuento.setEnabled(false);
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextAreaReservas = new javax.swing.JTextArea();
        jTextAreaReservas.setEnabled(false);


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombre.setText("Nombre");

        jLabelApellidos.setText("Apellidos");

        jRadioButtonTipo.setText("VIP");
        jRadioButtonTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButtonTipoActionPerformed(evt);
            }
        });

        jFormattedTextFieldDescuento.setEnabled(false);
        jLabelDNI.setText("DNI");

        jLabelDescuento.setText("Descuento");

        jLabelPuntos.setText("Puntos");

        
        jButtonAceptar.setText("Buscar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        
        jButtonCancelar.setVisible(false);
        jTextAreaReservas.setColumns(20);
        jTextAreaReservas.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButtonTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDescuento)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPuntos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNombre)
                                        .addGap(29, 29, 29)
                                        .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelApellidos)
                                            .addComponent(jLabelDNI))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldApellidos))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextAreaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidos)
                            .addComponent(jFormattedTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNI)
                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextAreaReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescuento)
                    .addComponent(jLabelPuntos)
                    .addComponent(jFormattedTextFieldPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(15, 15, 15))
        );
        //Borra el los datos correspondiente al cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        		//Borra lo anterior
                jFormattedTextFieldDNI.setText("");
                jFormattedTextFieldDescuento.setText("");
                jFormattedTextFieldNombre.setText("");
                jFormattedTextFieldPuntos.setText("");
                jFormattedTextFieldApellidos.setText("");
        		
            }
        });
        pack();
    }// </editor-fold>                        

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
    	 
    	ControladorImp.getInstancia().execute(Evento.MOSTRAR_CLIENTE, jFormattedTextFieldDNI.getText());
        // TODO add your handling code here:
    }   
    private void jRadioButtonTipoActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	jFormattedTextFieldDescuento.setText("");
        jFormattedTextFieldPuntos.setText(""); 
    	if(jRadioButtonTipo.isSelected()){
             //email
             jFormattedTextFieldDescuento.setEnabled(true);
             jFormattedTextFieldPuntos.setEnabled(false);

             
         }
         else{
             //email
        	 jFormattedTextFieldDescuento.setEnabled(false);
             jFormattedTextFieldPuntos.setEnabled(true);

            }    
    	 }   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMostrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormattedTextFieldApellidos;
    private javax.swing.JFormattedTextField jFormattedTextFieldDNI;
    private javax.swing.JFormattedTextField jFormattedTextFieldDescuento;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombre;
    private javax.swing.JFormattedTextField jFormattedTextFieldPuntos;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPuntos;
    private javax.swing.JRadioButton jRadioButtonTipo;
    private javax.swing.JTextArea jTextAreaReservas;

    // End of variables declaration                 
    @Override
	public void actualizar(int id_evento_vista, Object datos) {
		//Borra lo anterior
    	
    	 
         jFormattedTextFieldDescuento.setText("");
         jFormattedTextFieldNombre.setText("");
         jFormattedTextFieldPuntos.setText("");
         jFormattedTextFieldApellidos.setText("");
		
         if(id_evento_vista == EventoVista.MOSTRAR_CLIENTE_EXITO){
     		TransferCliente t = (TransferCliente) datos;
     		
     		jFormattedTextFieldNombre.setText(t.getNombre());
     		jFormattedTextFieldApellidos.setText(t.getApellidos());
     			
     		
     		if(TransferClienteVip.class == t.getClass()){
     			jRadioButtonTipo.setSelected(true);
     			
     			jFormattedTextFieldDescuento.setText((String.valueOf(((TransferClienteVip)t).getDescuento())));
     		}
     		else if(TransferClienteStandar.class == t.getClass()){
     			jRadioButtonTipo.setSelected(false);
     	
     			jFormattedTextFieldPuntos.setText((String.valueOf(((TransferClienteStandar)t).getPuntosAcumulados())));
     		}
     	
 			//IDs de las facturas
     		
     		jTextAreaReservas.append(" ID Reservas \n\n");
     		
 			for(int i: t.getId_reservas_cliente()){
 				jTextAreaReservas.append(" " + String.valueOf(i).toString() + "\n"); 
 			}
     		
     	}
 		else if(id_evento_vista == EventoVista.MOSTRAR_CLIENTE_FALLO){
 			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el cliente que se desea mostrar", "Mostrar Cliente", JOptionPane.ERROR_MESSAGE);
 		}
		
	}
}
