/**
 * 
 */
package PrimeraEntrega.Presentacion;

import java.awt.BorderLayout;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;



/**
 * 
 * @author Daniel 2.0
 */
public class PanelPrincipal extends javax.swing.JFrame {

	public PanelPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		pestanaCliente = new javax.swing.JMenu();
		botonNuevoCliente = new javax.swing.JMenuItem();
		botonBorrarCliente = new javax.swing.JMenuItem();
		botonModifcarCliente = new javax.swing.JMenuItem();
		botonMostrarCliente = new javax.swing.JMenuItem();
		botonMostrarClientes = new javax.swing.JMenuItem();
		pestanaHabitacion = new javax.swing.JMenu();
		botonNuevaHabitacion = new javax.swing.JMenuItem();
		botonBorrarHabitacion = new javax.swing.JMenuItem();
		botonModificarHabitacion = new javax.swing.JMenuItem();
		botonMostrarHabitacion = new javax.swing.JMenuItem();
		botonMostrarHabitaciones = new javax.swing.JMenuItem();
		pestanaReserva = new javax.swing.JMenu();
		botonNuevaReserva = new javax.swing.JMenuItem();
		botonBorrarReserva = new javax.swing.JMenuItem();
		botonModificarReserva = new javax.swing.JMenuItem();
		botonMostrarReserva = new javax.swing.JMenuItem();
		botonMostrarReservas = new javax.swing.JMenuItem();
		botonAsignarReserva = new javax.swing.JMenuItem();
		pestanaEmpleado = new javax.swing.JMenu();
		botonNuevoEmpleado = new javax.swing.JMenuItem();
		botonBajaEmpleado = new javax.swing.JMenuItem();
		botonMostrarEmpleado = new javax.swing.JMenuItem();
		botonMostrarEmpleados = new javax.swing.JMenuItem();
		botonAsignarTarea = new javax.swing.JMenuItem();
		pestanaDepartamento = new javax.swing.JMenu();
		botonNuevoDepartamento = new javax.swing.JMenuItem();
		botonBajaDepartamento = new javax.swing.JMenuItem();
		botonMostrarDepartamento = new javax.swing.JMenuItem();
		botonMostrarDepartamentos = new javax.swing.JMenuItem();
		pestanaTarea = new javax.swing.JMenu();
		botonNuevaTarea = new javax.swing.JMenuItem();
		botonBajaTarea = new javax.swing.JMenuItem();
		botonMostrarTarea = new javax.swing.JMenuItem();
		botonMostrarTareas = new javax.swing.JMenuItem();
		
		botonMostrarClientesReservasSuperadas = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		// setIconImage(Constants.icono);
		setResizable(false);
		
		/*
		Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono.png"));
		setIconImage(icono);
		*/
		
		this.setTitle("MSHoteles");
		
		pestanaCliente.setText("Cliente");
;
		botonNuevoCliente.setText("Nuevo Cliente");
		botonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevoClienteActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonNuevoCliente);
;
		botonBorrarCliente.setText("Borrar Cliente");
		botonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarClienteActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonBorrarCliente);

		botonModifcarCliente.setText("Modifcar Cliente");
		botonModifcarCliente.setActionCommand("Modificar Cliente");
		botonModifcarCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarClienteActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonModifcarCliente);

		botonMostrarCliente.setText("Mostrar Cliente");
		botonMostrarCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarClienteActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonMostrarCliente);

		botonMostrarClientes.setText("Mostrar Clientes");
		botonMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarClientesActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonMostrarClientes);
		
		botonMostrarClientesReservasSuperadas.setText("Mostrar Clientes Superan Reservas");
		botonMostrarClientesReservasSuperadas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarClientesReservasSuperadasActionPerformed(evt);
			}
		});
		pestanaCliente.add(botonMostrarClientesReservasSuperadas);

		jMenuBar1.add(pestanaCliente);

		pestanaHabitacion.setText("Habitacion");

		botonNuevaHabitacion.setText("Nueva Habitacion");
		botonNuevaHabitacion.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevaHabitacionActionPerformed(evt);
					}
				});
		pestanaHabitacion.add(botonNuevaHabitacion);

		botonBorrarHabitacion.setText("Borrar Habitacion");
		pestanaHabitacion.add(botonBorrarHabitacion);
		botonBorrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarHabitacionActionPerformed(evt);
			}
		});

		botonModificarHabitacion.setText("Modificar Habitacion");
		pestanaHabitacion.add(botonModificarHabitacion);
		botonModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarHabitacionActionPerformed(evt);
			}
		});

		botonMostrarHabitacion.setText("Mostrar Habitacion");
		pestanaHabitacion.add(botonMostrarHabitacion);
		botonMostrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarHabitacionActionPerformed(evt);
			}
		});

		botonMostrarHabitaciones.setText("Mostrar Habitaciones");
		pestanaHabitacion.add(botonMostrarHabitaciones);
		botonMostrarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarHabitacionesActionPerformed(evt);
			}
		});

		jMenuBar1.add(pestanaHabitacion);

		pestanaReserva.setText("Reserva");

		botonNuevaReserva.setText("Nueva Reserva");
		botonNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevaReservaActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonNuevaReserva);

		botonBorrarReserva.setText("Borrar Reserva");
		botonBorrarReserva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarReservaActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonBorrarReserva);

		botonModificarReserva.setText("Modificar Reserva");
		botonModificarReserva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarReservaActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonModificarReserva);

		botonMostrarReserva.setText("Mostrar Reserva");
		botonMostrarReserva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarReservaActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonMostrarReserva);

		botonMostrarReservas.setText("Mostrar Reservas");
		botonMostrarReservas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarReservasActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonMostrarReservas);
		
		botonAsignarReserva.setText("Asignar Reserva");
		botonAsignarReserva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAsignarReservaActionPerformed(evt);
			}
		});
		pestanaReserva.add(botonAsignarReserva);

		jMenuBar1.add(pestanaReserva);

		pestanaEmpleado.setText("Empleado");

		botonNuevoEmpleado.setText("Nuevo empleado");
		botonNuevoEmpleado
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevoEmpleadoActionPerformed(evt);
					}
				});
		pestanaEmpleado.add(botonNuevoEmpleado);

		botonBajaEmpleado.setText("Baja empleado");
		botonBajaEmpleado
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonBajaEmpleadoActionPerformed(evt);
					}
				});
		pestanaEmpleado.add(botonBajaEmpleado);
		

		botonMostrarEmpleado.setText("Mostrar empleado");
		botonMostrarEmpleado
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarEmpleadoActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonMostrarEmpleado);

		botonMostrarEmpleados.setText("Mostrar empleados");
		
		
		botonMostrarEmpleados
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarEmpleadosActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonMostrarEmpleados);
	

		botonAsignarTarea.setText("Asignar tarea");
		botonAsignarTarea
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAsignarTareaActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonAsignarTarea);

		jMenuBar1.add(pestanaEmpleado);

		pestanaDepartamento.setText("Departamento");

		botonNuevoDepartamento.setText("Nuevo departamento");
		botonNuevoDepartamento
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevoDepartamentoActionPerformed(evt);
					}
				});
		pestanaDepartamento.add(botonNuevoDepartamento);

		botonBajaDepartamento.setText("Baja departamento");
		botonBajaDepartamento
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonBajaDepartamentoActionPerformed(evt);
					}
				});
		pestanaDepartamento.add(botonBajaDepartamento);

		botonMostrarDepartamento.setText("Mostrar departamento");
		botonMostrarDepartamento
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarDepartamentoActionPerformed(evt);
			}
		});
		pestanaDepartamento.add(botonMostrarDepartamento);

		botonMostrarDepartamentos.setText("Mostrar departamentos");
		botonMostrarDepartamentos
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarDepartamentosActionPerformed(evt);
			}
		});
		pestanaDepartamento.add(botonMostrarDepartamentos);

		jMenuBar1.add(pestanaDepartamento);

		pestanaTarea.setText("Tarea");

		botonNuevaTarea.setText("Nueva tarea");
		botonNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevaTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonNuevaTarea);

		botonBajaTarea.setText("Baja tarea");
		botonBajaTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBajaTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonBajaTarea);

		botonMostrarTarea.setText("Mostrar tarea");
		botonMostrarTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonMostrarTarea);

		botonMostrarTareas.setText("Mostrar tareas");
		botonMostrarTareas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarTareasActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonMostrarTareas);

		jMenuBar1.add(pestanaTarea);

		setJMenuBar(jMenuBar1);

		ImageIcon image = new ImageIcon("res/logo.png");

		this.setIconImage(image.getImage());
		
		JLabel label = new JLabel("", image, JLabel.CENTER);
		
		JPanel panel = new JPanel(new BorderLayout());
		
		panel.add( label, BorderLayout.CENTER );
		
		this.add(panel);
		
		JLabel descripcion = new JLabel("Copyrigth MSHoteles 2015-2016");
		
		
		descripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); 
		
		panel.add( descripcion, BorderLayout.SOUTH );
		
		pack();
	}// </editor-fold>

	/*
	//ACCIONES HABITACIONES
	private void botonNuevaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		NuevaHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarHabitacion.obtenerInstancia().setVisible(true);
	
	}
	
	private void botonModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarHabitaciones.obtenerInstancia().mostrar();
		MostrarHabitaciones.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES ClienteS
	private void botonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoCliente.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarCliente.obtenerInstancia().setVisible(true);
	}
	
	private void botonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarCliente.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarClienteActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarCliente.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarClientes.obtenerInstancia().mostrar();
		MostrarClientes.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarClientesReservasSuperadasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarClientesSuperanReservas.obtenerInstancia().mostrar();
		MostrarClientesSuperanReservas.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES ReservaS
	private void botonNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {
		NuevaReserva.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarReservaActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarReserva.obtenerInstancia().setVisible(true);
	}
	
	private void botonModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarReserva.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarReservaActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarReserva.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarReservas.obtenerInstancia().mostrar();
		MostrarReservas.obtenerInstancia().setVisible(true);
	}
	
	private void botonAsignarReservaActionPerformed(java.awt.event.ActionEvent evt) {
		AsignarReserva.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES EMPLEADOS
	private void botonNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoEmpleado.obtenerInstancia().setVisible(true);
	}
	
	private void botonBajaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		BajaEmpleado.obtenerInstancia().setVisible(true);
	
	}
	private void botonMostrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		
		MostrarEmpleado.obtenerInstancia().setVisible(true);
		
	}
	private void botonMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {
	
		MostrarEmpleados.obtenerInstancia().mostrar();
		MostrarEmpleados.obtenerInstancia().setVisible(true);
	}
	private void botonAsignarTareaActionPerformed(java.awt.event.ActionEvent evt) {
		
		AsignarTarea.obtenerInstancia().setVisible(true);
	}

	//ACCIONES DEPARTAMENTOS

	private void botonNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonBajaDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
			BajaDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarDepartamentos.obtenerInstancia().mostrar();
		MostrarDepartamentos.obtenerInstancia().setVisible(true);
	}

	//ACCIONES TAREAS
	private void botonNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {
	  NuevaTarea.obtenerInstancia().setVisible(true);
	}

	private void botonBajaTareaActionPerformed(java.awt.event.ActionEvent evt) {
		BajaTarea.obtenerInstancia().setVisible(true);
	}
	private void botonMostrarTareaActionPerformed(java.awt.event.ActionEvent evt) {
	MostrarTarea.obtenerInstancia().setVisible(true);
	}
	private void botonMostrarTareasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarTareas.obtenerInstancia().mostrar();
		MostrarTareas.obtenerInstancia().setVisible(true);
	}
	
	
	*/
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PanelPrincipal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	
	private javax.swing.JMenuItem botonAsignarTarea;
	private javax.swing.JMenuItem botonBajaDepartamento;
	private javax.swing.JMenuItem botonBajaEmpleado;
	private javax.swing.JMenuItem botonBajaTarea;
	private javax.swing.JMenuItem botonBorrarReserva;
	private javax.swing.JMenuItem botonBorrarHabitacion;
	private javax.swing.JMenuItem botonBorrarCliente;
	private javax.swing.JMenuItem botonModifcarCliente;
	private javax.swing.JMenuItem botonModificarReserva;
	private javax.swing.JMenuItem botonModificarHabitacion;
	private javax.swing.JMenuItem botonMostrarDepartamento;
	private javax.swing.JMenuItem botonMostrarDepartamentos;
	private javax.swing.JMenuItem botonMostrarEmpleado;
	private javax.swing.JMenuItem botonMostrarEmpleados;
	private javax.swing.JMenuItem botonMostrarReserva;
	private javax.swing.JMenuItem botonMostrarReservas;
	private javax.swing.JMenuItem botonMostrarHabitacion;
	private javax.swing.JMenuItem botonMostrarHabitaciones;
	private javax.swing.JMenuItem botonMostrarCliente;
	private javax.swing.JMenuItem botonMostrarClientes;
	private javax.swing.JMenuItem botonMostrarTarea;
	private javax.swing.JMenuItem botonMostrarTareas;
	private javax.swing.JMenuItem botonNuevaReserva;
	private javax.swing.JMenuItem botonNuevaHabitacion;
	private javax.swing.JMenuItem botonNuevaTarea;
	private javax.swing.JMenuItem botonNuevoDepartamento;
	private javax.swing.JMenuItem botonNuevoEmpleado;
	private javax.swing.JMenuItem botonNuevoCliente;
	private javax.swing.JMenuItem botonAsignarReserva;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenu pestanaDepartamento;
	private javax.swing.JMenu pestanaEmpleado;
	private javax.swing.JMenu pestanaReserva;
	private javax.swing.JMenu pestanaHabitacion;
	private javax.swing.JMenu pestanaCliente;
	private javax.swing.JMenu pestanaTarea;
	// End of variables declaration
	
	private javax.swing.JMenuItem botonMostrarClientesReservasSuperadas;

}
